name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EdricChan03/action-build-deploy-ghpages@v2
        with:
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          skip_deploy: 'true'
