name: Build & Deploy

on:
  # push:
    # types: [ closed ]
    # branches: [ master ]
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EdricChan03/action-build-deploy-ghpages@v2
        with:
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          skip_deploy: 'false'
